[Service]
Environment=LIBCAMERA_SOFTISP_MODE=cpu
Environment="SPA_PLUGIN_DIR=/home/joerg/Dokumente/surface-camera/sp7-pipewire-test/spa:/usr/lib64/spa-0.2"
Environment="LD_LIBRARY_PATH=/home/joerg/Dokumente/surface-camera/libcamera/build-sp7/src/libcamera:/home/joerg/Dokumente/surface-camera/libcamera/build-sp7/src/libcamera/base"
